[package]
name = "hello"
version = "0.1.0"
authors = ["Ludea <ludealol.olol@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "hello-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "feat/mobile" }

[dependencies]
anyhow = "1.0.56"
log = "0.4.11"
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "feat/mobile" }
wry = "0.20"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9.0"
jni = "0.19.0"
paste = "1.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
mobile-entry-point = "0.1.0"
env_logger = "0.9.0"
