name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0
    - name: Install cargo mobile 
      run: cargo install --git https://github.com/tauri-apps/cargo-mobile 
    - name: Setup NDK 
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r22b
        add-to-path: false
    - name: Init Android project 
      run: cargo mobile init 
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Build Android project 
      run: cargo android build
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Gradle
      run: cd gen/android/hello && ./gradlew build
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - uses: actions/upload-artifact@v3
      with:
        name: Hello.apk
        path: gen/android/hello/app/build/outputs/apk/arm64/debug/app-arm64-debug.apk 
  IOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install cargo-mobile
      run: cargo install --git https://github.com/tauri-apps/cargo-mobile 
    - name: init 
      run: cargo mobile init
    - name: build
      run: cargo apple build
