name: Build

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup NDK 
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: true
    - name: install app dependencies 
      run:  yarn && yarn build
    - name: Init Android Studio Project
      run: yarn tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: gradle
    - name: Build apk
      run: yarn tauri android build --split-per-abi --debug
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - uses: actions/upload-artifact@v3
      with:
        name: apks
        path: |
          src-tauri/gen/android/hello/app/build/outputs/apk/**/**/*.apk
          
  IOS:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install app dependencies and build it
      run: yarn && yarn build
    - name: Init Xcode Project
      run: yarn tauri ios init
    - name: Build IOS app
      run: yarn tauri ios build

