name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0
    - name: Install cargo mobile 
      run: cargo install --git https://github.com/tauri-apps/cargo-mobile 
    - name: Setup NDK 
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r22b
        add-to-path: false
    - name: Iinit Android project 
      run: cargo mobile init 
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Build Android project 
      run: cargo android build 
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Gradle
      run: |
        ls gen/android/hello
        cd gen/android/hello && ./gradlew build
