name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11' 
    - name: Clone Tauri next branch
      run: |
        git clone https://github.com/tauri-apps/tauri
        cd tauri && git checkout next
    - name: Build tauri next branch
      run: |
        cd tauri/tooling/cli
        cargo build
    - name: Setup NDK 
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        local-cache: true
    - name: Debug
      run: |
        yarn
        ls 
        echo foo
        ls node_modules
    - name: Debug again
      run: | 
        DEBUG="vite-tsconfig-paths" node_modules/.bin/vite dev
    - name: install app dependencies 
      run:  yarn && yarn build
    - name: Init Android Studio Project
      run: tauri/tooling/cli/target/debug/cargo-tauri android init
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Build apk
      run: tauri/tooling/cli/target/debug/cargo-tauri android build --split-per-abi --debug
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - uses: actions/upload-artifact@v3
      with:
        name: apks
        path: |
          src-tauri/gen/android/hello/app/build/outputs/apk/**/**/*.apk
          
  IOS:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build tauri next branch
      run: |
        git clone https://github.com/tauri-apps/tauri
        cd tauri && git checkout next
        cd tooling/cli/node
        yarn
        yarn build
    - name: install app dependencies and build it
      run: yarn && yarn build
    - name: Init Xcode Project
      run: yarn tauri ios init
    - name: Build IOS app
      run: yarn tauri ios build

